export const ROUTES = {
  admin: "admin",
  about: "about",
  macro: "macro",
  macroGeopolitical: "macro/geopolitical",
  macroOutlooks: "macro/macro-outlooks",
  policyMonetary: "macro/policy-monetary",
  esg: "sectoral/esg",
  regional: "sectoral/regional",
  deepDives: "sectoral/deep-dives",
  data: "data",
  economicCalendar: "data/economic-calendar",
  marketDashboard: "data/market-dashboard",
  marketOverview: "data/market-overview",
  blog: "blog",
  blog101: "blog/economics-101",
  blogLabNotes: "blog/lab-notes",
  analisis: "analisis",
  contact: "contact",
} as const;
